### ISSUE TITLE
Zabalení bucketu

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui-storage#2]
Pokud v quick search něco vyhledám, zobrazí se mi defaultně výpis bucketů rozbalený (jsou vidět tabulky uvnitř), nejde to ale zabalit. Pokud chci ve "velkém" projektu něco najít, nutí mě to nakonec scrollovat mnohem víc než bez vyhledávání.

![image](https://cloud.githubusercontent.com/assets/1427901/12386611/03e1a95a-bdc7-11e5-8824-858753ed5dca.png)

**Comment by ujovlado** [comment]
This issue was moved to keboola/storage-api-console#34
